version: "3"

services:
  dev:
    image: eosio/eos-dev:v1.2.3
    working_dir: '/work'
    volumes:
      - ./build:/work/build
      - ./contracts:/work/contracts
      - ./eos-wallet:/root/eosio-wallet
    links:
      - nodeos
  nodeos:
    image: eosio/eos:v1.2.4
    volumes:
      - ./nodeos_data:/mnt/dev/data
    command: /bin/bash -c "nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false"
